-- MySQL Script generated by MySQL Workbench
-- Fri Dec 20 14:35:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Site` (
  `idParametres_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(30) NOT NULL,
  `Prénom` VARCHAR(30) NOT NULL,
  `numéro_de_tél` INT(15) NOT NULL,
  `addresse_mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idParametres_utilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contact` (
  `idContact` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(30) NOT NULL,
  `addresse` VARCHAR(30) NULL,
  `numéro_de_tél` INT(10) NOT NULL,
  `addresse_mail` VARCHAR(45) NOT NULL,
  `Page_idPage` INT NOT NULL,
  `Page_Menu_idMenu` INT NOT NULL,
  `Page_Langue_idLangue` INT NOT NULL,
  PRIMARY KEY (`idContact`, `Page_idPage`, `Page_Menu_idMenu`, `Page_Langue_idLangue`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `email_admin` VARCHAR(45) NOT NULL,
  `mdp_admin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Langue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Langue` (
  `idLangue` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idLangue`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `idMenu` INT NOT NULL AUTO_INCREMENT,
  `log_admin` VARCHAR(20) NOT NULL,
  `email_admin` VARCHAR(20) NOT NULL,
  `mdp_admin` VARCHAR(20) NOT NULL,
  `Langue_idLangue` INT NOT NULL,
  PRIMARY KEY (`idMenu`, `Langue_idLangue`),
  INDEX `fk_Menu_Langue1_idx` (`Langue_idLangue` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_Langue1`
    FOREIGN KEY (`Langue_idLangue`)
    REFERENCES `mydb`.`Langue` (`idLangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lien_externe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lien_externe` (
  `idLien_externe` INT NOT NULL AUTO_INCREMENT,
  `Menu_idMenu` INT NOT NULL,
  PRIMARY KEY (`idLien_externe`, `Menu_idMenu`),
  INDEX `fk_Lien_externe_Menu1_idx` (`Menu_idMenu` ASC) VISIBLE,
  CONSTRAINT `fk_Lien_externe_Menu1`
    FOREIGN KEY (`Menu_idMenu`)
    REFERENCES `mydb`.`Menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fichier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fichier` (
  `idFichier` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFichier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`page_corp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`page_corp` (
  `idpage_corp` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(45) NOT NULL,
  `Sous_titre` VARCHAR(45) NOT NULL,
  `Fichier_idFichier` INT NOT NULL,
  PRIMARY KEY (`idpage_corp`, `Fichier_idFichier`),
  INDEX `fk_page_corp_Fichier1_idx` (`Fichier_idFichier` ASC) VISIBLE,
  CONSTRAINT `fk_page_corp_Fichier1`
    FOREIGN KEY (`Fichier_idFichier`)
    REFERENCES `mydb`.`Fichier` (`idFichier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recommendation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recommendation` (
  `idRecommendation` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `commentaire` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRecommendation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Page` (
  `idPage` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(30) NOT NULL,
  `affige_page` INT(2) NOT NULL,
  `Menu_idMenu` INT NOT NULL,
  `Langue_idLangue` INT NOT NULL,
  `Lien_externe_idLien_externe` INT NOT NULL,
  `Lien_externe_Menu_idMenu` INT NOT NULL,
  `Contact_idContact` INT NOT NULL,
  `Contact_Page_idPage` INT NOT NULL,
  `Contact_Page_Menu_idMenu` INT NOT NULL,
  `Contact_Page_Langue_idLangue` INT NOT NULL,
  `page_corp_idpage_corp` INT NOT NULL,
  `Recommendation_idRecommendation` INT NOT NULL,
  PRIMARY KEY (`idPage`, `Menu_idMenu`, `Langue_idLangue`, `Lien_externe_idLien_externe`, `Lien_externe_Menu_idMenu`, `Contact_idContact`, `Contact_Page_idPage`, `Contact_Page_Menu_idMenu`, `Contact_Page_Langue_idLangue`, `page_corp_idpage_corp`, `Recommendation_idRecommendation`),
  INDEX `fk_Page_Menu1_idx` (`Menu_idMenu` ASC) VISIBLE,
  INDEX `fk_Page_Langue1_idx` (`Langue_idLangue` ASC) VISIBLE,
  INDEX `fk_Page_Lien_externe1_idx` (`Lien_externe_idLien_externe` ASC, `Lien_externe_Menu_idMenu` ASC) VISIBLE,
  INDEX `fk_Page_Contact1_idx` (`Contact_idContact` ASC, `Contact_Page_idPage` ASC, `Contact_Page_Menu_idMenu` ASC, `Contact_Page_Langue_idLangue` ASC) VISIBLE,
  INDEX `fk_Page_page_corp1_idx` (`page_corp_idpage_corp` ASC) VISIBLE,
  INDEX `fk_Page_Recommendation1_idx` (`Recommendation_idRecommendation` ASC) VISIBLE,
  CONSTRAINT `fk_Page_Menu1`
    FOREIGN KEY (`Menu_idMenu`)
    REFERENCES `mydb`.`Menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Page_Langue1`
    FOREIGN KEY (`Langue_idLangue`)
    REFERENCES `mydb`.`Langue` (`idLangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Page_Lien_externe1`
    FOREIGN KEY (`Lien_externe_idLien_externe` , `Lien_externe_Menu_idMenu`)
    REFERENCES `mydb`.`Lien_externe` (`idLien_externe` , `Menu_idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Page_Contact1`
    FOREIGN KEY (`Contact_idContact` , `Contact_Page_idPage` , `Contact_Page_Menu_idMenu` , `Contact_Page_Langue_idLangue`)
    REFERENCES `mydb`.`Contact` (`idContact` , `Page_idPage` , `Page_Menu_idMenu` , `Page_Langue_idLangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Page_page_corp1`
    FOREIGN KEY (`page_corp_idpage_corp`)
    REFERENCES `mydb`.`page_corp` (`idpage_corp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Page_Recommendation1`
    FOREIGN KEY (`Recommendation_idRecommendation`)
    REFERENCES `mydb`.`Recommendation` (`idRecommendation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parametres_utilisateur_has_Page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parametres_utilisateur_has_Page` (
  `Parametres_utilisateur_idParametres_utilisateur` INT NOT NULL,
  `Page_idPage` INT NOT NULL,
  `Page_Menu_idMenu` INT NOT NULL,
  `Page_Langue_idLangue` INT NOT NULL,
  `Page_Lien_externe_idLien_externe` INT NOT NULL,
  `Page_Lien_externe_Menu_idMenu` INT NOT NULL,
  `Page_Contact_idContact` INT NOT NULL,
  `Page_Contact_Page_idPage` INT NOT NULL,
  `Page_Contact_Page_Menu_idMenu` INT NOT NULL,
  `Page_Contact_Page_Langue_idLangue` INT NOT NULL,
  PRIMARY KEY (`Parametres_utilisateur_idParametres_utilisateur`, `Page_idPage`, `Page_Menu_idMenu`, `Page_Langue_idLangue`, `Page_Lien_externe_idLien_externe`, `Page_Lien_externe_Menu_idMenu`, `Page_Contact_idContact`, `Page_Contact_Page_idPage`, `Page_Contact_Page_Menu_idMenu`, `Page_Contact_Page_Langue_idLangue`),
  INDEX `fk_Parametres_utilisateur_has_Page_Page1_idx` (`Page_idPage` ASC, `Page_Menu_idMenu` ASC, `Page_Langue_idLangue` ASC, `Page_Lien_externe_idLien_externe` ASC, `Page_Lien_externe_Menu_idMenu` ASC, `Page_Contact_idContact` ASC, `Page_Contact_Page_idPage` ASC, `Page_Contact_Page_Menu_idMenu` ASC, `Page_Contact_Page_Langue_idLangue` ASC) VISIBLE,
  INDEX `fk_Parametres_utilisateur_has_Page_Parametres_utilisateur1_idx` (`Parametres_utilisateur_idParametres_utilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Parametres_utilisateur_has_Page_Parametres_utilisateur1`
    FOREIGN KEY (`Parametres_utilisateur_idParametres_utilisateur`)
    REFERENCES `mydb`.`Site` (`idParametres_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parametres_utilisateur_has_Page_Page1`
    FOREIGN KEY (`Page_idPage` , `Page_Menu_idMenu` , `Page_Langue_idLangue` , `Page_Lien_externe_idLien_externe` , `Page_Lien_externe_Menu_idMenu` , `Page_Contact_idContact` , `Page_Contact_Page_idPage` , `Page_Contact_Page_Menu_idMenu` , `Page_Contact_Page_Langue_idLangue`)
    REFERENCES `mydb`.`Page` (`idPage` , `Menu_idMenu` , `Langue_idLangue` , `Lien_externe_idLien_externe` , `Lien_externe_Menu_idMenu` , `Contact_idContact` , `Contact_Page_idPage` , `Contact_Page_Menu_idMenu` , `Contact_Page_Langue_idLangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
